title: "ASPInsiders Official Home"

baseurl: ""
url: "//aspinsiders.com"

repository: aspinsiders/aspinsiders.github.io

safe: true
google_analytics_enabled: true

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - serve.sh

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
